steps:
- id: 'build image'
  name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/hayplatform-283607/github.com/haypost-dev/micro-order:$COMMIT_SHA'
    - '..'
    - '-f'
    - './src/Services/Identity/Identity.API/Dockerfile'
  timeout: 1000s

